# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_model_category'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ManyToManyField(to='models.Model'),
        ),
    ]
