# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170422_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
    ]
