# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='booking',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
