# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170422_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='code',
        ),
    ]
