# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170422_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
