# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Pending'), (3, b'Installation Bid'), (4, b'Created'), (5, b'Paid'), (6, b'Payment Received'), (7, b'Deliver'), (8, b'completed'), (9, b'canceled')], default=1),
        ),
    ]
