# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170426_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Pending'), (3, b'Installation Bid'), (4, b'Created'), (5, b'Paid'), (6, b'Payment Approved'), (7, b'Deliver'), (8, b'Completed'), (9, b'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Approved'), (3, b'Rejected')], default=1),
        ),
    ]
