# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 19:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170506_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
