# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('orders', '0012_auto_20170515_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banks.Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
