# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20170517_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='correction_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='value',
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='sender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
