# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170517_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentConfirmation',
            new_name='Payment',
        ),
    ]
