# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20170517_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
