# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import spargo.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=spargo.core.utils.FilenameGenerator(prefix=b'product-photo'))),
                ('is_active', models.BooleanField(default=True, verbose_name=b'active')),
            ],
        ),
    ]
