# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='photo', max_length=50),
            preserve_default=False,
        ),
    ]
