# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 04:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('models', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, verbose_name=b'active')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
                ('photos', models.ManyToManyField(related_name='types', to='photos.Photo')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
