# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='products', to='photos.Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='types.Type'),
        ),
    ]
