# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('products', '0002_auto_20170422_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(to='models.Model'),
        ),
    ]
