# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0001_initial'),
        ('products', '0003_auto_20170422_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types.Type'),
            preserve_default=False,
        ),
    ]
