# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0003_subtype'),
        ('products', '0006_auto_20170506_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtype_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='types.SubType'),
        ),
    ]
