# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-28 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170821_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subtype_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='types.SubType'),
            preserve_default=False,
        ),
    ]
