# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 16:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('regular_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('regular_estimated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oke_cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('oke_estimated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yes_cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('yes_estimated', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
