# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import spargo.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0002_remove_type_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=spargo.core.utils.FilenameGenerator(prefix=b'sub-type-photo'))),
                ('is_active', models.BooleanField(default=True, verbose_name=b'active')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types.Type')),
            ],
        ),
    ]
