# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import spargo.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, validators=[spargo.core.validators.validate_mobile_phone], verbose_name=b'Mobile Number'),
        ),
    ]
